export const ubicacionesBase = [
    { "id": 1, "name": "ABREGO" },
    { "id": 2, "name": "ACACIAS" },
    { "id": 3, "name": "ACEVEDO" },
    { "id": 4, "name": "AGUA DE DIOS" },
    { "id": 5, "name": "AGUACHICA" },
    { "id": 6, "name": "AGUAZUL" },
    { "id": 7, "name": "AGUSTIN CODAZZI" },
    { "id": 8, "name": "AIPE" },
    { "id": 9, "name": "ALBANIA" },
    { "id": 10, "name": "ALGECIRAS" },
    { "id": 11, "name": "ANAPOIMA" },
    { "id": 12, "name": "ANDALUCIA" },
    { "id": 13, "name": "ANGOSTURA" },
    { "id": 14, "name": "ANOLAIMA" },
    { "id": 15, "name": "ANTIOQUIA" },
    { "id": 16, "name": "APARTADO" },
    { "id": 17, "name": "APULO" },
    { "id": 18, "name": "ARACATACA" },
    { "id": 19, "name": "ARATOCA" },
    { "id": 20, "name": "ARAUCA" },
    { "id": 21, "name": "ARAUQUITA" },
    { "id": 22, "name": "ARBELAEZ" },
    { "id": 23, "name": "ARBOLETES" },
    { "id": 24, "name": "ARJONA" },
    { "id": 25, "name": "ARMENIA" },
    { "id": 26, "name": "ASTREA" },
    { "id": 27, "name": "AYAPEL" },
    { "id": 28, "name": "BAJO SAN JUAN" },
    { "id": 29, "name": "BALBOA" },
    { "id": 30, "name": "BARANOA" },
    { "id": 31, "name": "BARAYA" },
    { "id": 32, "name": "BARBACOAS" },
    { "id": 33, "name": "BARBOSA" },
    { "id": 34, "name": "BARICHARA" },
    { "id": 35, "name": "BARRANCABERMEJA" },
    { "id": 36, "name": "BARRANCAS" },
    { "id": 37, "name": "BARRANCO DE LOBA" },
    { "id": 38, "name": "BARRANQUILLA" },
    { "id": 39, "name": "BECERRIL" },
    { "id": 40, "name": "BELEN DE LOS ANDAQUIES" },
    { "id": 41, "name": "BELEN DE UMBRIA" },
    { "id": 42, "name": "BELLO" },
    { "id": 43, "name": "BOAVITA" },
    { "id": 44, "name": "BOGOTA" },
    { "id": 45, "name": "BOLIVAR" },
    { "id": 46, "name": "BOSCONIA" },
    { "id": 47, "name": "BUCARAMANGA" },
    { "id": 48, "name": "BUCARASICA" },
    { "id": 49, "name": "BUENAVENTURA" },
    { "id": 50, "name": "BUENAVISTA" },
    { "id": 51, "name": "BUENOS AIRES" },
    { "id": 52, "name": "BUESACO" },
    { "id": 53, "name": "BUGA" },
    { "id": 54, "name": "BUGALAGRANDE" },
    { "id": 55, "name": "CABRERA" },
    { "id": 56, "name": "CACERES" },
    { "id": 57, "name": "CACHIRA" },
    { "id": 58, "name": "CAIMITO" },
    { "id": 59, "name": "CAJAMARCA" },
    { "id": 60, "name": "CAJICA" },
    { "id": 61, "name": "CALAMAR" },
    { "id": 62, "name": "CALDAS" },
    { "id": 63, "name": "CALDONO" },
    { "id": 64, "name": "CALI" },
    { "id": 65, "name": "CALOTO" },
    { "id": 66, "name": "CAMPOALEGRE" },
    { "id": 67, "name": "CANALETE" },
    { "id": 68, "name": "CANDELARIA" },
    { "id": 69, "name": "CANTAGALLO" },
    { "id": 70, "name": "CAÑASGORDAS" },
    { "id": 71, "name": "CAPARRAPI" },
    { "id": 72, "name": "CAPITANEJO" },
    { "id": 73, "name": "CAQUEZA" },
    { "id": 74, "name": "CARACOLI" },
    { "id": 75, "name": "CAREPA" },
    { "id": 76, "name": "CARMEN DE BOLIVAR" },
    { "id": 77, "name": "CAROLINA" },
    { "id": 78, "name": "CARTAGENA" },
    { "id": 79, "name": "CARTAGENA DE CHAIRA" },
    { "id": 80, "name": "CARTAGO" },
    { "id": 81, "name": "CASTILLA LA NUEVA" },
    { "id": 82, "name": "CAUCASIA" },
    { "id": 83, "name": "CERETE" },
    { "id": 84, "name": "CERINZA" },
    { "id": 85, "name": "CHAPARRAL" },
    { "id": 86, "name": "CHARALA" },
    { "id": 87, "name": "CHIA" },
    { "id": 88, "name": "CHIGORODO" },
    { "id": 89, "name": "CHIMA" },
    { "id": 90, "name": "CHIMICHAGUA" },
    { "id": 91, "name": "CHINACOTA" },
    { "id": 92, "name": "CHINCHINA" },
    { "id": 93, "name": "CHIPATA" },
    { "id": 94, "name": "CHIQUINQUIRA" },
    { "id": 95, "name": "CHIRIGUANA" },
    { "id": 96, "name": "CHITA" },
    { "id": 97, "name": "CHOCONTA" },
    { "id": 98, "name": "CIENAGA" },
{ "id": 99, "name": "CIENAGA DE ORO" },
{ "id": 100, "name": "CIMITARRA" },
{ "id": 101, "name": "COELLO" },
{ "id": 102, "name": "COGUA" },
{ "id": 103, "name": "COLOMBIA" },
{ "id": 104, "name": "COLOSO" },
{ "id": 105, "name": "COMBITA" },
{ "id": 106, "name": "CONCEPCION" },
{ "id": 107, "name": "CONDOTO" },
{ "id": 108, "name": "CONFINES" },
{ "id": 109, "name": "CONSACA" },
{ "id": 110, "name": "CONVENCION" },
{ "id": 111, "name": "COPACABANA" },
{ "id": 112, "name": "CORDOBA" },
{ "id": 113, "name": "CORINTO" },
{ "id": 114, "name": "COROMORO" },
{ "id": 115, "name": "COROZAL" },
{ "id": 116, "name": "COTA" },
{ "id": 117, "name": "COTORRA" },
{ "id": 118, "name": "COVEÑAS" },
{ "id": 119, "name": "COYAIMA" },
{ "id": 120, "name": "CRAVO NORTE" },
{ "id": 121, "name": "CUBARA" },
{ "id": 122, "name": "CUCUTA" },
{ "id": 123, "name": "CUMARAL" },
{ "id": 124, "name": "CUMARIBO" },
{ "id": 125, "name": "CUMBAL" },
{ "id": 126, "name": "CUMBITARA" },
{ "id": 127, "name": "CUNDAY" },
{ "id": 128, "name": "CURILLO" },
{ "id": 129, "name": "CURUMANI" },
{ "id": 130, "name": "DABEIBA" },
{ "id": 131, "name": "DAGUA" },
{ "id": 132, "name": "DIBULLA" },
{ "id": 133, "name": "DISTRACCION" },
{ "id": 134, "name": "DOSQUEBRADAS" },
{ "id": 135, "name": "DUITAMA" },
{ "id": 136, "name": "EBEJICO" },
{ "id": 137, "name": "EL BAGRE" },
{ "id": 138, "name": "EL BANCO" },
{ "id": 139, "name": "EL CARMEN" },
{ "id": 140, "name": "EL CARMEN DE BOLIVAR" },
{ "id": 141, "name": "EL COCUY" },
{ "id": 142, "name": "EL COLEGIO" },
{ "id": 143, "name": "EL COPEY" },
{ "id": 144, "name": "EL DIFICIL" },
{ "id": 145, "name": "EL DONCELLO" },
{ "id": 146, "name": "EL DOVIO" },
{ "id": 147, "name": "EL ESPINO" },
{ "id": 148, "name": "EL GUACAMAYO" },
{ "id": 149, "name": "EL GUAMO" },
{ "id": 150, "name": "EL MOLINO" },
{ "id": 151, "name": "EL PAUJIL" },
{ "id": 152, "name": "EL PEÑON" },
{ "id": 153, "name": "EL PIÑON" },
{ "id": 154, "name": "EL PLAYON" },
{ "id": 155, "name": "EL RETORNO" },
{ "id": 156, "name": "EL ROBLE" },
{ "id": 157, "name": "EL TAMBO" },
{ "id": 158, "name": "EL ZULIA" },
{ "id": 159, "name": "ENVIGADO" },
{ "id": 160, "name": "ESPINAL" },
{ "id": 161, "name": "FACATATIVA" },
{ "id": 162, "name": "FALAN" },
{ "id": 163, "name": "FLANDES" },
{ "id": 164, "name": "FLORENCIA" },
{ "id": 165, "name": "FLORIDA" },
{ "id": 166, "name": "FLORIDABLANCA" },
{ "id": 167, "name": "FONSECA" },
{ "id": 168, "name": "FORTUL" },
{ "id": 169, "name": "FREDONIA" },
{ "id": 170, "name": "FRESNO" },
{ "id": 171, "name": "FRONTINO" },
{ "id": 172, "name": "FUNDACION" },
{ "id": 173, "name": "FUNZA" },
{ "id": 174, "name": "FUSAGASUGA" },
{ "id": 175, "name": "GACHETA" },
{ "id": 176, "name": "GALAPA" },
{ "id": 177, "name": "GALERAS" },
{ "id": 178, "name": "GAMARRA" },
{ "id": 179, "name": "GARZON" },
{ "id": 180, "name": "GENOVA" },
{ "id": 181, "name": "GIRARDOT" },
{ "id": 182, "name": "GIRARDOTA" },
{ "id": 183, "name": "GIRON" },
{ "id": 184, "name": "GRAMALOTE" },
{ "id": 185, "name": "GRANADA" },
{ "id": 186, "name": "GUACAMAYAS" },
{ "id": 187, "name": "GUACARI" },
{ "id": 188, "name": "GUACHUCAL" },
{ "id": 189, "name": "GUADALAJARA DE BUGA" },
{ "id": 190, "name": "GUADALUPE" },
{ "id": 191, "name": "GUADUAS" },
{ "id": 192, "name": "GUAITARILLA" },
{ "id": 193, "name": "GUAMAL" },
{ "id": 194, "name": "GUAMO" },
{ "id": 195, "name": "GUARNE" },
{ "id": 196, "name": "GUASCA" },
{ "id": 197, "name": "GUATAVITA" },
{ "id": 198, "name": "GUATEQUE" },
{ "id": 199, "name": "GUAYABAL DE SIQUIMA" },
{ "id": 200, "name": "GUAYATA" },
{ "id": 201, "name": "HATO" },
{ "id": 202, "name": "HATO COROZAL" },
{ "id": 203, "name": "HATONUEVO" },
{ "id": 204, "name": "HONDA" },
{ "id": 205, "name": "IBAGUE" },
{ "id": 206, "name": "ICONONZO" },
{ "id": 207, "name": "INIRIDA" },
{ "id": 208, "name": "IPIALES" },
{ "id": 209, "name": "IQUIRA" },
{ "id": 210, "name": "ISNOS" },
{ "id": 211, "name": "ISTMINA" },
{ "id": 212, "name": "ITAGUI" },
{ "id": 213, "name": "JAMUNDI" },
{ "id": 214, "name": "JARDIN" },
{ "id": 215, "name": "JENESANO" },
{ "id": 216, "name": "JERICO" },
{ "id": 217, "name": "JESUS MARIA" },
{ "id": 218, "name": "JUAN DE ACOSTA" },
{ "id": 219, "name": "JUNIN" },
{ "id": 220, "name": "LA APARTADA" },
{ "id": 221, "name": "LA BELLEZA" },
{ "id": 222, "name": "LA CALERA" },
{ "id": 223, "name": "LA DORADA" },
{ "id": 224, "name": "LA ESPERANZA" },
{ "id": 225, "name": "LA ESTRELLA" },
{ "id": 226, "name": "LA GLORIA" },
{ "id": 227, "name": "LA JAGUA DE IBIRICO" },
{ "id": 228, "name": "LA JAGUA DEL PILAR" },
{ "id": 229, "name": "LA MACARENA" },
{ "id": 230, "name": "LA MERCED" },
{ "id": 231, "name": "LA MESA" },
{ "id": 232, "name": "LA MONTAÑITA" },
{ "id": 233, "name": "LA PALMA" },
{ "id": 234, "name": "LA PAZ" },
{ "id": 235, "name": "LA PLATA" },
{ "id": 236, "name": "LA TEBAIDA" },
{ "id": 237, "name": "LA UNION" },
{ "id": 238, "name": "LA VEGA" },
{ "id": 239, "name": "LABATECA" },
{ "id": 240, "name": "LANDAZURI" },
{ "id": 241, "name": "LEBRIJA" },
{ "id": 242, "name": "LEGUIZAMO" },
{ "id": 243, "name": "LEIVA" },
{ "id": 244, "name": "LEJANIAS" },
{ "id": 245, "name": "LERIDA" },
{ "id": 246, "name": "LETICIA" },
{ "id": 247, "name": "LIBANO" },
{ "id": 248, "name": "LIBORINA" },
{ "id": 249, "name": "LLORO" },
{ "id": 250, "name": "LOPEZ DE MICAY" },
{ "id": 251, "name": "LORICA" },
{ "id": 252, "name": "LOS PATIOS" },
{ "id": 253, "name": "LOS SANTOS" },
{ "id": 254, "name": "LOURDES" },
{ "id": 255, "name": "LURUACO" },
{ "id": 256, "name": "MADRID" },
{ "id": 257, "name": "MAGANGUE" },
{ "id": 258, "name": "MAICAO" },
{ "id": 259, "name": "MAJAGUAL" },
{ "id": 260, "name": "MALAGA" },
{ "id": 261, "name": "MALAMBO" },
{ "id": 262, "name": "MALLAMA" },
{ "id": 263, "name": "MAMBITA" },
{ "id": 264, "name": "MANATI" },
{ "id": 265, "name": "MANAURE" },
{ "id": 266, "name": "MANI" },
{ "id": 267, "name": "MANIZALES" },
{ "id": 268, "name": "MANZANARES" },
{ "id": 269, "name": "MARACAIBO" },
{ "id": 270, "name": "MARIA LA BAJA" },
{ "id": 271, "name": "MARINILLA" },
{ "id": 272, "name": "MARIQUITA" },
{ "id": 273, "name": "MARQUETALIA" },
{ "id": 274, "name": "MEDELLIN" },
{ "id": 275, "name": "MEDINA" },
{ "id": 276, "name": "MELGAR" },
{ "id": 277, "name": "MERCADERES" },
{ "id": 278, "name": "MESETAS" },
{ "id": 279, "name": "MIRAFLORES" },
{ "id": 280, "name": "MITU" },
{ "id": 281, "name": "MOCOA" },
{ "id": 282, "name": "MOGOTES" },
{ "id": 283, "name": "MOLAGOVITA" },
{ "id": 284, "name": "MOMIL" },
{ "id": 285, "name": "MOMPOS" },
{ "id": 286, "name": "MONIQUIRA" },
{ "id": 287, "name": "MONTE LIBANO" },
{ "id": 288, "name": "MONTEBELLO" },
{ "id": 289, "name": "MONTECRISTO" },
{ "id": 290, "name": "MONTELIBANO" },
{ "id": 291, "name": "MONTERIA" },
{ "id": 292, "name": "MORALES" },
{ "id": 293, "name": "MORELIA" },
{ "id": 294, "name": "MORROA" },
{ "id": 295, "name": "MOSQUERA" },
{ "id": 296, "name": "MUTATA" },
{ "id": 297, "name": "NARIÑO" },
{ "id": 298, "name": "NATAGA" },
{ "id": 299, "name": "NATAGAIMA" },
{ "id": 300, "name": "NECHI" },
{ "id": 301, "name": "NECOCLI" },
{ "id": 302, "name": "NEIRA" },
{ "id": 303, "name": "NEIVA" },
{ "id": 304, "name": "NEMOCON" },
{ "id": 305, "name": "NORCASIA" },
{ "id": 306, "name": "OCANA" },
{ "id": 307, "name": "OCAÑA" },
{ "id": 308, "name": "OIBA" },
{ "id": 309, "name": "ONZAGA" },
{ "id": 310, "name": "ORTEGA" },
{ "id": 311, "name": "OTANCHE" },
{ "id": 312, "name": "PACHO" },
{ "id": 313, "name": "PACORA" },
{ "id": 314, "name": "PAICOL" },
{ "id": 315, "name": "PAILITAS" },
{ "id": 316, "name": "PAIPA" },
{ "id": 317, "name": "PALERMO" },
{ "id": 318, "name": "PALMAS DEL SOCORRO" },
{ "id": 319, "name": "PALMIRA" },
    { "id": 320, "name": "PAMPLONA" },
    { "id": 321, "name": "PAMPLONITA" },
    { "id": 322, "name": "PASTO" },
    { "id": 323, "name": "PATIA" },
    { "id": 324, "name": "PAUNA" },
    { "id": 325, "name": "PAZ DE ARIPORO" },
    { "id": 326, "name": "PELAYA" },
    { "id": 327, "name": "PENSILVANIA" },
    { "id": 328, "name": "PEREIRA" },
    { "id": 329, "name": "PIEDECUESTA" },
    { "id": 330, "name": "PINILLOS" },
    { "id": 331, "name": "PITALITO" },
    { "id": 332, "name": "PIVIJAY" },
    { "id": 333, "name": "PLANADAS" },
    { "id": 334, "name": "PLANETA RICA" },
    { "id": 335, "name": "PLATO" },
    { "id": 336, "name": "POLICARPA" },
    { "id": 337, "name": "POLONUEVO" },
    { "id": 338, "name": "PONEDERA" },
    { "id": 339, "name": "POPAYAN" },
    { "id": 340, "name": "PORE" },
    { "id": 341, "name": "PRADERA" },
    { "id": 342, "name": "PRADO" },
    { "id": 343, "name": "PROVIDENCIA" },
    { "id": 344, "name": "PUEBLO NUEVO" },
    { "id": 345, "name": "PUEBLO RICO" },
    { "id": 346, "name": "PUEBLO VIEJO" },
    { "id": 347, "name": "PUEBLOVIEJO" },
    { "id": 348, "name": "PUENTE NACIONAL" },
    { "id": 349, "name": "PUERRES" },
    { "id": 350, "name": "PUERTO ASIS" },
    { "id": 351, "name": "PUERTO BERRIO" },
    { "id": 352, "name": "PUERTO BOYACA" },
    { "id": 353, "name": "PUERTO CARREÑO" },
    { "id": 354, "name": "PUERTO COLOMBIA" },
    { "id": 355, "name": "PUERTO ESCONDIDO" },
    { "id": 356, "name": "PUERTO GUZMAN" },
    { "id": 357, "name": "PUERTO LEGUIZAMO" },
    { "id": 358, "name": "PUERTO LIBERTADOR" },
    { "id": 359, "name": "PUERTO NARE" },
    { "id": 360, "name": "PUERTO NARIÑO" },
    { "id": 361, "name": "PUERTO PARRA" },
    { "id": 362, "name": "PUERTO RICO" },
    { "id": 363, "name": "PUERTO RONDON" },
    { "id": 364, "name": "PUERTO SALGAR" },
    { "id": 365, "name": "PUERTO SANTANDER" },
    { "id": 366, "name": "PUERTO TEJADA" },
    { "id": 367, "name": "PUERTO TRIUNFO" },
    { "id": 368, "name": "PUERTO WILCHES" },
    { "id": 369, "name": "PURIFICACION" },
    { "id": 370, "name": "QUIBDO" },
    { "id": 371, "name": "QUINCHIA" },
    { "id": 372, "name": "REMOLINO" },
    { "id": 373, "name": "REPELON" },
    { "id": 374, "name": "RICAURTE" },
    { "id": 375, "name": "RIO DE ORO" },
    { "id": 376, "name": "RIO VIEJO" },
    { "id": 377, "name": "RIOBLANCO" },
    { "id": 378, "name": "RIOHACHA" },
    { "id": 379, "name": "RIONEGRO" },
    { "id": 380, "name": "RIOSUCIO" },
    { "id": 381, "name": "RIVERA" },
    { "id": 382, "name": "ROBERTO PAYAN" },
    { "id": 383, "name": "ROLDANILLO" },
    { "id": 384, "name": "RONCESVALLES" },
    { "id": 385, "name": "ROVIRA" },
    { "id": 386, "name": "SABANA DE TORRES" },
    { "id": 387, "name": "SABANA LARGA" },
    { "id": 388, "name": "SABANALARGA" },
    { "id": 389, "name": "SAHAGUN" },
    { "id": 390, "name": "SALDANA" },
    { "id": 391, "name": "SALDAÑA" },
    { "id": 392, "name": "SAMANA" },
    { "id": 393, "name": "SAMPUES" },
    { "id": 394, "name": "SAN AGUSTIN" },
    { "id": 395, "name": "SAN ALBERTO" },
    { "id": 396, "name": "SAN ANDRES" },
    { "id": 397, "name": "SAN ANDRES DE TUMACO" },
    { "id": 398, "name": "SAN ANTERO" },
    { "id": 399, "name": "SAN ANTONIO" },
    { "id": 400, "name": "SOCORRO" },
        { "id": 401, "name": "SOGAMOSO" },
        { "id": 402, "name": "SOLEDAD" },
        { "id": 403, "name": "SONSON" },
        { "id": 404, "name": "SOPLAVIENTO" },
        { "id": 405, "name": "SORACA" },
        { "id": 406, "name": "SUAN" },
        { "id": 407, "name": "SUAREZ" },
        { "id": 408, "name": "SUAZA" },
        { "id": 409, "name": "SUBACHOQUE" },
        { "id": 410, "name": "SUCRE" },
        { "id": 411, "name": "SURATA" },
        { "id": 412, "name": "SUTAMARCHAN" },
        { "id": 413, "name": "SUTATAUSA" },
        { "id": 414, "name": "TABIO" },
        { "id": 415, "name": "TADO" },
        { "id": 416, "name": "TAMARA" },
        { "id": 417, "name": "TAME" },
        { "id": 418, "name": "TAURAMENA" },
        { "id": 419, "name": "TELLO" },
        { "id": 420, "name": "TERUEL" },
        { "id": 421, "name": "TESALIA" },
        { "id": 422, "name": "TIBASOSA" },
        { "id": 423, "name": "TIBIRITA" },
        { "id": 424, "name": "TIBU" },
        { "id": 425, "name": "TIERRALTA" },
        { "id": 426, "name": "TIMBIO" },
        { "id": 427, "name": "TIPACOQUE" },
        { "id": 428, "name": "TITIRIBI" },
        { "id": 429, "name": "TOCA" },
        { "id": 430, "name": "TOCAIMA" },
        { "id": 431, "name": "TOCANCIPA" },
        { "id": 432, "name": "TOLEDO" },
        { "id": 433, "name": "TOLU" },
        { "id": 434, "name": "TOLU VIEJO" },
        { "id": 435, "name": "TOPAIPI" },
        { "id": 436, "name": "TORO" },
        { "id": 437, "name": "TRINIDAD" },
        { "id": 438, "name": "TUBARA" },
        { "id": 439, "name": "TULUA" },
        { "id": 440, "name": "TUMACO" },
        { "id": 441, "name": "TUNJA" },
        { "id": 442, "name": "TUQUERRES" },
        { "id": 443, "name": "TURBACO" },
        { "id": 444, "name": "TURBO" },
        { "id": 445, "name": "TURMEQUE" },
        { "id": 446, "name": "UBALA" },
        { "id": 447, "name": "UBATE" },
        { "id": 448, "name": "UMBITA" },
        { "id": 449, "name": "UNE" },
        { "id": 450, "name": "URIBIA" },
        { "id": 451, "name": "URUMITA" },
        { "id": 452, "name": "USIACURI" },
        { "id": 453, "name": "UTICA" },
        { "id": 454, "name": "VALENCIA" },
        { "id": 455, "name": "VALLE DE SAN JOSE" },
        { "id": 456, "name": "VALLEDUPAR" },
        { "id": 457, "name": "VALPARAISO" },
        { "id": 458, "name": "VEGACHI" },
        { "id": 459, "name": "VELEZ" },
        { "id": 460, "name": "VENECIA" },
        { "id": 461, "name": "VERGARA" },
        { "id": 462, "name": "VICTORIA" },
        { "id": 463, "name": "VILLA CARO" },
        { "id": 464, "name": "VILLA DEL ROSARIO" },
        { "id": 465, "name": "VILLA MARIA" },
        { "id": 466, "name": "VILLA NUEVA" },
        { "id": 467, "name": "VILLA ROSARIO" },
        { "id": 468, "name": "VILLAGARZON" },
        { "id": 469, "name": "VILLAGOMEZ" },
        { "id": 470, "name": "VILLANUEVA" },
        { "id": 471, "name": "VILLAVICENCIO" },
        { "id": 472, "name": "VILLAVIEJA" },
        { "id": 473, "name": "VILLETA" },
        { "id": 474, "name": "VISTAHERMOSA" },
        { "id": 475, "name": "YACOPI" },
        { "id": 476, "name": "YACUANQUER" },
        { "id": 477, "name": "YARUMAL" },
        { "id": 478, "name": "YONDO" },
        { "id": 479, "name": "YOPAL" },
        { "id": 480, "name": "YUMBO" },
        { "id": 481, "name": "ZAMBRANO" },
        { "id": 482, "name": "ZARZAL" },
        { "id": 483, "name": "ZIPAQUIRA" }
    
];
