export const clientesSucursales = {
    "Transelca S.A E.S.P.": ["Tanselca S.E Bolívar", "Sede Puerto Colombia", "Transelca S.E Ternera", "Transelca S.E Caracoli", "Transelca S.E Termocartagena", "Sede Barranquilla", "Transelca Sede Soledad", "Transelca SE Sabanalarga", "Transelca Drummond", "Transelca Termocol", "Transelca S.E Santa Marta", "Transelca S.E Gecelca", "Transelca S.E Valledupar", "Transelca S.E. Cuestecitas", "Transelca S.E Copey", "Transelca S.E Termoguajira", "Transelca Fundación", "Transelca SE Rio"],
    "Petropolar Sucursal Colombia": ["Proyecto  saxofon"],
    "DIRECCIÓN SECCIONAL DE ADMINISTRACIÓN JUDICIAL DE CUNDINAMARCA": ["SEDE PALACIO DE JUSTICIA VILLETA", "PALACIO DE JUSTICIA SEDE ALTERNA  SOACHA", "PALACIO DE JUSTICIA - GIRARDOT", "JUZGADO PROMISCUO MUNICIPAL DE VILLETA", "SEDE NUEVA - Juzgado Cuarto Penal del Circuito y Segundo  Ejecucion de Penas y Medidas de Seguridad", "SEDE JUDICIAL CAN", "PALACIO DE JUSTICIA DE FUSAGASUGA", "JUZGADOS MENORES Y ADOLECENTES FUSAGASUGA", "JUZGADO FAMILIA", "JUZGADOS DE EJECUCIÓN DE PENAS Y MEDIDAS DE SEGURIDAD", "JUZGADOS PROMISCUOS DE GUADUAS", "JUZGADOS PENALES DEL CIRCUITO MUNICIPAL GIRARDOT", "ARCHIVOS PENALES GIRARDOT", "SEDE JUZGADO PROMISCUO MUNICIPAL DE SIBATÉ", "PALACIO DE JUSTICIA LA MESA", "SEDE JUDICIAL DE PACHO", "JUZGADO 2 FAMILIA ZIPAQUIRA", "JUZGADO 1 CIVIL MUNICIPAL ZIPAQUIRÁ", "JUZGADO 1 LABORAL - 2 EJECUCION Y PENAS ZIPAQUIRA", "JUZGADO 1 FAMILIA ZIPAQUIRA", "JUZGADO 2 CIVIL DEL CIRCUITO ZIPAQUIRA", "JUZGADO PENAL MUNICIPAL DE UBATE", "JUZGADOS 1/2 PENAL-3 CIVIL MUNICIPAL CHIA 1", "JUZGADOS 1/2 CIVIL MUNICIPAL CHIA", "SEDE JUDICIAL CAQUEZA", "SEDE JUDICIAL LA PEDRERA - AMAZONAS", "SEDE JUDICIAL DE LA PALMA", "SEDE JUDICIAL PUERTO NARIÑO AMAZONAS", "JUZGADO 3 CIVIL DEL CIRCUITO - ZIPAQUIRA", "EDIFICIO SAN MARTIN PISOS 30/31 COMISION SECCIONAL DE DISCIPLINA JUDICIAL DE C/MARCA - PISO 32 CONCEJO SECCIONAL DE DISCIPLINA JUDICIAL DE C/MARCA", "NUEVA SEDE RAMA JUDICIAL CHÍA / JUZGADOS CIVILES Y PENALES MUNICIPALES", "JUZGADO PRIMERO Y SEGUNDO PROMISCUO MUNICIPAL DE SIBATE", "PALACIO DE JUSTICIA SEDE NUEVA FUNZA", "PALACIO DE JUSTICIA SEDE ALTERNA FUNZA", "PALACIO DE JUSTICIA FUNZA PPAL", "JUZGADO 2 LABORAL Y DE FAMILIA DE FUNZA", "SEDE JUDICIAL DE MOSQUERA", "JUZGADO 2 CIVIL MUNICIPAL DE MADRID", "PALACIO DE JUSTICIA DE CHOCONTA", "SEDE JUDICIAL FACATATIVÁ", "SEDE JUDICIAL DE MADRID", "SEDE JUDICIAL GACHETA", "Juzgado municipal de San Antonio del Tequendama", "SEDE JUDICIAL DE YACOPI", "DIRECCIÓN SECCIONAL DE ADMINISTRACIÓN JUDICIAL DEL AMAZONAS.", "PALACIO DE JUSTICIA SOACHA PPAL", "JUZGADO PROMISCUO MUNICIPAL EL COLEGIO", "LOTE RAMA GIRARDOT", "JUZGADO PENAL MUNICIPAL ZIPAQUIRÁ", "JUZGADO PRIMERO PENAL DEL CIRCUITO ZIPAQUIRA", "JUZGADO ADMINISTRATIVO ZIPAQUIRA", "SEDE JUDICIAL BODEGA DE INVENTARIOS N° 3", "TRIBUNALES DE BOGOTA Y CUNDINAMARCA"],
    "SEGURIDAD Y VIGILANCIA COLOMBIANA SEVICOL LTDA": ["Agencia Sevicol Monteria", "Sevicol Ltda. Sede Bogotá", "SEDE BARRANCABERMEJA", "SEVICOL SUCURSAL VILLAVICENCIO", "Agencia Barranquilla", "SEVICOL LTDA", "Sevicol Agencia Medellín", "Agencia Aguachica", "SEVICOL AGENCIA CALI", "Sevicol Sede Cúcuta", "Sevicol Sede Principal Bucaramanga", "SEVICOL CARTAGENA"],
    "TERRAMAGMA S.A.S - BUNKERING": ["TERRAMAGMA S.A.S BUNKERING"],
    "Redcol Holding": ["New Cambridge. Campestre", "New Cambridge Sede Cañaveral", "Newport. Ruitoque Bajo", "COLEGIO NEW CAMBRIDGE", "Little Cambridge", "Newport School. Caracoli", "Colegio Santa Francisca Romana - Pachas", "Colegio Bureche Santa Marta", "Británico Cartagena Anillo vial"],
    "CONGREGACIÓN DE HERMANAS TERCIARIAS CAPUCHINAS DE LA SAGRADA FAMILIA": ["Escuela normal Superior Antonia Santos"],
    "BANCO BILBAO VISCAYA ARGENTARIA COLOMBIA S.A. BBVA": ["BBVA FONDO DE EMPLEADOS", "BBVA EDIFICIO - TEUSAQUILLO", "BBVA SALAS DE FORMACION CALLE 93 (MAGISTRALES)", "BBVA SALAS DE CAPACITACION CALLE 93 (MEZANINE)", "BBVA CENTRO HIPOTECARIO - EDIFICIO ASTORIAS", "BBVA EDIFICIO SANTAMONICA CALI", "BBVA PARQUEADERO - CALI", "BBVA SEDE TERRITORIAL CENTRO BOGOTA", "BBVA EDIFICIO DIRECCION GENERAL", "BBVA BODEGA TECNOLOGIA"],
    "Bancolombia": ["Edificio Mixto Torre Sur PH", "PREDIO AUTOS DE LA SABANA BANCOLOMBIA"],
    "Alianza Diagnostica S.A.": ["ALIANZA DIAGNOSTICA S.A  - Sotomayor", "ALIANZA DIAGNOSTICA SEDE BUCARICA", "Alianza Diagnostica. Lagos 1", "ALIANZA DIAGNOSTICA Sede UAB Cabecera", "ALIANZA DIAGNOSTICA Sede Cabecera", "ALIANZA DIAGNOSTICA Sede Calle 45", "ALIANZA DIAGNOSTICA Sede Giron"],
    "Sociedad Portuaria Transmarsyp S.A.": ["Sede Principal Cartagena"],
    "PETROSANTANDER COLOMBIA INC": ["Petrosantander Corazón West", "Petrosantander Batería Salinas", "Petrosantander Principal Payoa"],
    "ISAGEN S.A. E.S.P.": ["ISAGEN Central Hidroeléctrica Sogamoso", "ISAGEN Central Hidroeléctrica Rio Amoya- La Esperanza", "ISAGEN Central Hidroeléctrica Miel", "Parque Eólico Guajira 1", "BOSQUES SOLARES DE BOLIVAR"],
    "Cooperativa Especializada de ahorro y Credito Crediservir": ["CREDISERVIR CONVENCION", "CREDISERVIR CONVENCIÓN", "CREDISERVIR SANTA CLARA", "CREDISERVIR CENTRO", "CREDISERVIR AGUACHICA", "CREDISERVIR ABREGO", "CREDISERVIR RIO DE ORO"],
    "OMNICHANNEL TECHNOLOGIES S.A.S.": ["OMNICHANNEL TCHNOLOGIES S.A.S OFICINA 201 EDIFICIO TERPEL"],
    "Certificado Nacional Tecnicomecánico S.A.": ["CNT San Francisco", "CNT Piedecuesta", "CNT Bucaramanga"],
    "Conjunto Residencial Buenavista": ["Conjunto Residencial Buenavista"],
    "Conjunto Residencial Mirador Del Oriente": ["Conjunto Residencial Mirador Del Oriente"],
    "Alea Herrajes S.A.S": ["Sede unica", "Alea Herrajes S.A.S"],
    "Conjunto Residencial Remanso": ["Conjunto Residencial Remanso"],
    "Confipetrol S.A.S": ["OFICINA", "LOTE KILOMETRO 11"],
    "Edificio 37 Vip Center": ["Edificio 37 Vip Center"],
    "San Silvestre Condominio": ["San Silvestre Condominio"],
    "Fundación Servicio Jurídico Popular": ["Fundación Servicio Jurídico Popular"],
    "Conjunto Residencial Calamari Reservado P H": ["Conjunto Residencial Calamari Reservado P H"],
    "Penagos Hermanos": ["Local Bucaramanga"],
    "Conjunto Natura Ecoparque Empresarial": ["Conjunto Natura Ecoparque Empresarial"],
    "Procesadora Nacional Cigarrillera S.A. PRONALCI S.A": ["PRONALCI"],
    "Hoteles de Barranca S.A.S.": ["Hoteles de Barranca S.A.S."],
    "Conjunto Residencial Colinas De Yerbabuena": ["Conjunto Residencial Colinas De Yerbabuena"],
    "Conjunto Residencial Altos De Yerbabuena": ["Conjunto Residencial Altos De Yerbabuena"],
    "ZELESTRA COLOMBIA S.A.S E.S.P.": ["ZELESTRA"],
    "Oriental Hermanos": ["Oriental Hermanos"],
    "CARBONES DEL CERREJON LIMITED": ["Terminal Terrestre AMTUR Riohacha", "CERREJON CONJUNTO LA HERRADURA", "CERREJON OFICINAS EDIFICIO TORRE MAS 92"],
    "MEDIC COLOMBIA S.A.S": ["MEDIC ENVIGADO", "MEDIC ITAGUI", "MEDIC CALDAS", "MEDIC PUNTO CLAVE", "MEDIC PUNTO DE LA ORIENTAL", "MEDIC BELLO", "MEDIC- BODEGA", "Sede Administrativa/Bodega Principal MEDIC COLOMBIA", "MEDIC BARBOSA"],
    "ACEROS Y ALUMINIO DEL ORIENTE S.A.S.": ["ACEROS Y ALUMINIO DEL ORIENTE S.A.S."],
    "EDIFICIO SAN MARTIN PROPIEDAD HORIZONTAL": ["EDIFICIO SAN MARTIN"],
    "Apergy Usa, Inc. Sucursal Colombia": ["Apergy Base No. 2", "Sede Barrancabermeja"],
    "Edificio Suramericana Bogotá": ["Edificio SuramericanaBogotá"],
    "AGUAS NACIONALES EPM SA ESP": ["PLANTA PTAR BELLO"],
    "CONSTRUCCIONES, INTERVENTORIAS Y CONSULTORIAS S.A.S. CONSTRUCTORA INCO S.A.S.": ["CONSTRUCTORA INCO S.A.S.- SEDE MEDELLIN"],
    "EDIFICIO BEAUTY GARDEN": ["EDIFICIO BEAUTY GARDEN"],
    "TELEANTIOQUIA": ["TELEANTIOQUIA"],
    "Sociedad Pediátrica De Los Andes S.A.S.": ["Sede Principal de Servicios -  SPLA"],
    "Colegio Gimnasio Vermont Medellín SAS": ["Sede MEDELLÍN"],
    "Bio D S. A.": ["BIO D Planta Facatativá"],
    "Asociación Para La Enseñanza Aspaen": ["Aspaen Sede Parnaso", "ASOCIACIÓN PARA LA ENSEÑANZA ASPAEN", "colegio Aspaen"],
    "Petroworks S.A.S": ["PETROWORKS Base Taller Gachacipá"],
    "Reyes Aristizábal Y Cía. Ltda.": ["Joyería Caracas"],
    "CLUB DEPORTIVO Y SOCIAL INTERNACIONAL": ["Sede Club de Golf"],
    "Halliburton Latín América Sucursal Colombia ": ["HALLIBURTON - Base Neiva", "HALLIBURTON - Base Villavicencio", "HALLIBURTON - Base Yopal", "HALLIBURTON - Base Barranquilla", "HALLIBURTON - Base Cota", "HALLIBURTON - Base Barrancabermeja"],
    "Casinos Entretenimiento De La Cuesta S.A.S": ["Casino bucaramanga", "Casino piedecuesta", "Casino C.C De la Cuesta"],
    "Tienda Stirpe Outlet": ["Tienda  Stirpe Outlet Centro", "Tienda Stirpe Outlet. Las Américas"],
    "Technip FMC": ["Technip FMC"],
    "Borets Services Ltda.": ["BORETS Planta Villavicencio"],
    "Conjunto Residencial Península": ["Conjunto Residencial Península"],
    "Vehículos Blindados De Colombia Ltda VEBLINCO": ["VEHÍCULOS BLINDADOS DE COLOMBIA LTDA", "Vehiculos Blindados de Colombia Ltda VEBLINCO"],
    "Obleas Floridablanca S.A.S.": ["Punto De Venta Obleas - BUCARAMANGA", "Punto De Venta Obleas - FLORIDABLANCA"],
    "Sigra S. A.": ["SIGRA S.A Hacienda la ilusión - Yopal"],
    "CORPORACION CLUB SOCIAL Y DEPORTIVO ECOPETROL BOGOTA": ["CLUB ECOPETROL"],
    "HDI SEGUROS COLOMBIA S.A.": ["SEDE SANTA SOFIA", "OFICINA PRINCIPAL CALLE 72"],
    "SAR ENERGY S A S EN REORGANIZACION": ["SAR ENERGY Base Principal"],
    "Consorcio OMIA SKF": ["Consorcio OMIA SKF", "Consorcio OMIA SKF 1"],
    "J.E. JAIMES INGENIEROS S.A.S.": ["J.E. JAIMES INGENIEROS S.A.S."],
    "JOYERIA Y RELOJERIA EL CORAL": ["JOYERIA Y RELOJERIA EL CORAL"],
    "Serviyarima S.A.S.": ["EDS serviyarima"],
    "Leasing Bancolombia": ["Bodega de Transportes Polo Sanchez - Leasing Bancolombia", "Bodega NIKE-Bancolombia."],
    "Restaurante El Gran Hong Kong Chino": ["Restaurante El Gran Hong Kong Chino"],
    "PROCTECK S.A.S": ["BASE PROCTEK TOCANCIPA"],
    "HQE - HIGH QUALITY ENGINEERING SAS": ["HQE - HIGH QUALITY ENGINEERING SAS"],
    "Fuller Pinto S.A.": ["FULLER PINTO Planta Fontibón", "FULLER PINTO Sede Administrativa Montevideo"],
    "Distribuciones Vía Medical De La Costa": ["DISTRIBUCIONES VIA MEDICAL DE LA COSTA"],
    "SERVICIOS DE SALUDO OCUPACIONAL S.A.S.": ["SERVICIOS DE SALUD OCUPACIONAL S.A.S."],
    "INHOMAR": ["INHOMAR LOTE RECORREDOR", "OFICINA PRINCIPAL TRANMARSYP"],
    "HARINAGRO S.A.": ["Harinagro Cartagena", "HARINAGRO S.A."],
    "Cartagena Container Terminal Operator SAS CCTO": ["CCTO Planta Cartagena"],
    "Atina Energy Services Corp Sucursal Colombia": ["Patio Barrancabermeja"],
    "Espumas Santander S.A.S.": ["Espumas Santander"],
    "GYPLAC": ["GYPLAC"],
    "PAPELERA FK S.A.S": ["PAPELERA FK S.A.S"],
    "Avícola Sinain Sas": ["Avicola Sinain", "Avicola Sinain Granja San Nicolas"],
    "CENTRO EMPRESARIAL SURAMERICANA": ["Centro Empresarial SURAMERICANA"],
    "SAFETECH SAS": ["SAFETECH SAS"],
    "Clínica Norte S.A.": ["CLINICA NORTE S.A."],
    "Empresa De Transporte Lebrija Limitada": ["EDS lebrija"],
    "Medicolombia Cannabis": ["Medicolombia Cannabis Sede Mesa de los santos"],
    "Ecodiesel Colombia S. A.": ["Planta Barrancabermeja"],
    "BANCO GNB SUDAMERIS": ["CIS SOTOMAYOR", "CIS PARAGUITAS", "CIS ALCALDIA"],
    "INGENIUX SOLUCIONES S.A.S.": ["INGENIUX S.A.S."],
    "PANAMERICANA LIBRERÍA Y PAPELERÍA S.A": ["PANAMERICANA LIBRERÍA Y PAPELERÍA S.A"],
    "Cooperativa De Ahorro Y Crédito De Trabajadores Activos Y Jubilados Copacredito": ["Sede administrativa"],
    "Conjunto Residencial La Cima": ["Conjunto Residencial La Cima"],
    "Centro Logístico Metropolitano": ["Centro logistico metropolitano"],
    "Canacol Energy": ["ESTACION JOBO", "ESTACION BETANIA", "ESTACIÓN CLARINETE", "ESTACIÓN SAN LUIS", "ESTACIÓN LA UNIÓN", "Estación Betania", "Canacol rancho hermoso 10", "Bloque Rancho Hermoso 4", "Bloque Rancho Hermoso 2. Canacol"],
    "Centro Internacional De Negocios La Triada": ["EDIFICIO LA TRIADA"],
    "Empresa Cooperativa De La Industria Petrolera Y Energética Copacentro ": ["Sede Barrancabermeja"],
    "Crezcamos S.A Empresa de Financiamiento": ["Crezcamos Oficina Bucaramanga DG"],
    "CUERPO DE BOMBEROS VOLUNTARIOS DE FLORIDABLANCA": ["BOMBEROS FLORIDABLANCA", "BOMBEROS BUCARICA"],
    "Edificio Montearroyo Propiedad Horizontal": ["Edificio Montearroyo Propiedad Horizontal"],
    "CARLOS ENRIQUE VALDIVIESO JIMENEZ (Notaria Segunda)": ["CARLOS ENRIQUE VALDIVIESO JIMENEZ (Notaria Segunda)"],
    "Arroces Y Cereales De La Costa S.A.": ["Arrocera japonesa"],
    "ESENTTIA S.A.": ["ESENTTIA SEDE ADMINISTRATIVA", "ESENTTIA EXPRESS TIENDA CARVAJAL", "ESENTTIA MASTERBATCH LTDA", "ESENTTIA PP"],
    "Instituto Colombiano De Normas Técnicas Y Certificación Icontec": ["Instituto Colombiano De Normas Técnicas Y Certificación Icontec"],
    "EDIFICIO 13-35": ["EDIFICIO 13-35"],
    "Cooperativa De Trabajadores De Colombia Coomuldenorte": ["Sede administrativa"],
    "Cooperativa Multiactiva Trabajadores Huem Coohem": ["COOHEM OFICINA PRINCIPAL"],
    "Laboratorios León": ["Sede principal. lab leon"],
    "BIOCONCENTRADOS": ["BIO CONCENTRADOS"],
    "AEI ARQUITECTURA E INTERIORES S.A.S": ["AEI ARQUITECTURA E INTERIORES S.A.S"],
    "AGENCIA NACIONAL DE INFRAESTRUCTURA (ANI)": ["AGENCIA NACIONAL DE INFRAESTRUCTURA (ANI)"],
    "Inversiones Camionero": ["Inversiones  Camionero"],
    "Conjunto Residencial Valle de Rocas": ["Conjunto Residencial Valle Rocas"],
    "Agrupación Zona Franca Santander": ["Complejo industrial"],
    "Colegio Chester Palmer": ["Colegio"],
    "Distribuciones Ibáñez Castilla": ["IBAÑEZ CASTILLA DISTRIBUCIONES CUCUTA"],
    "CÁMARA DE COMERCIO DE CASANARE": ["CÁMARA DE COMERCIO DE CASANARE"],
    "Coovolsa S. A": ["Coovolsa- Cantera"],
    "Higinio Camacho Yamaha Motos": ["Higinio Camacho Yamaha Motos"],
    "CONSEJO EPISCOPAL LATINOAMERICANO Y CARIBEÑO": ["CONSEJO EPISCOPAL LATINOAMERICANO Y CARIBEÑO"],
    "Antonio María Serrano Tapisander S.A.S.": ["Tapisander"],
    "FUNDACION COLOMBIA COLLEGE": ["FUNDACION COLOMBIA COLLEGE"],
    "Moto World": ["MOTO WORLD ORIENTE S.A."],
    "COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO COOPIGON": ["Coopigon"],
    "Extrucol S.A.": ["Extrucol planta parque industrial"],
    "Iboma S.A.S.": ["IBOMA S.A.S"],
    "Generadora Termocentro": ["Generadora Termocentro"],
    "EL RETEN DEL CASCO": ["EL RETEN DEL CASCO"],
    "NG BUSINESS GROUP S.A.S": ["NG BUSINESS GROUP S.A.S"],
    "American Pipe And Construction International": ["AMERICAN PIPE Lote-Obra"],
    "Cajasan": ["CAJASAN", "CAJASAN COLEGIO LAGOS 3"],
    "CAJA COOPERATIVA PETROLERA": ["CAJA COOPERATIVA PETROLERA"],
    "COOPERATIVA DE VOLQUETEROS DEL SARARE LTDA": ["COOPERATIVA DE VOLQUETEROS DEL SARARE LTDA"],
    "FMC TECHNOLOGIES INC": ["FMC TECHNOLOGIES INC"],
    "OPERACION Y MANTENIMIENTO INTEGRAL DE ACTIVOS COLOMBIA SAS": ["OPERACION Y MANTENIMIENTO INTEGRAL DE ACTIVOS COLOMBIA SAS"],
    "INPROYECT S.A.S": ["INPROYECT S.A.S"],
    "PROYECTO AGRUPADO CANACOL": ["PROYECTO AGRUPADO CANACOL"],
    "JICA MONTERÍA": ["JICA MONTERÍA"],
    "Empresa de Transporte Masivo del Valle de Aburrá Limitada": ["Empresa de Transporte Masivo del Valle de Aburrá Limitada"],
    "JULIAN DE JESUS SANCHEZ DUQUE": ["JULIAN DE JESUS SANCHEZ DUQUE"],
    "UNIÓN TEMPORAL SEVISEGK 2026": ["UNIÓN TEMPORAL SEVISEGK 2026"],
    "CONSORCIO MIRO SEGURIDAD LTDA- SEVICOL LTDA ISAGEN 2021-2023": ["CAJA"],
    "COOPERATIVA AGROINDUSTRIAL DE AVICULTORES DE SANTANDER": ["COOPERATIVA AGROINDUSTRIAL DE AVICULTORES DE SANTANDER"],
    "D & S S.A.S.": ["D & S S.A.S."],
    "PJT GASTOS PROYECTOS NACIONALES": ["PJT GASTOS PROYECTOS NACIONALES"],
    "PROPIEDAD HORIZONTAL EDIFICIO COMERCIAL CREDISERVIR": ["PROPIEDAD HORIZONTAL EDIFICIO COMERCIAL CREDISERVIR"],
    "PROYECTO AGRUPADO RUITOQUE": ["PROYECTO AGRUPADO RUITOQUE"],
    "SEGURIDAD DE OCCIDENTE LTDA": ["SEGURIDAD DE OCCIDENTE LTDA"],
    "AMERON INTERNATIONAL CORPORATION SUCURSAL COLOMBIA": ["AMERON INTERNATIONAL CORPORATION SUCURSAL COLOMBIA"],
    "CENIT TRANSPORTE Y LOGISTICA DE HIDROCARBUROS SAS": ["CENIT TRANSPORTE Y LOGISTICA DE HIDROCARBUROS SAS"],
    "CHUBB SEGUROS COLOMBIA  S A": ["CHUBB SEGUROS COLOMBIA  S A"],
    "DIAN 2023-2026": ["DIAN 2023-2026"],
    "ECOPETROL ESCOLTAS 2025": ["ECOPETROL ESCOLTAS 2025"],
    "FUNDACION JAPAN EXTERNAL TRADE ORGANIZATION": ["FUNDACION JAPAN EXTERNAL TRADE ORGANIZATION"],
    "NEOSTAR SEGURIDAD DE COLOMBIA LTDA": ["NEOSTAR SEGURIDAD DE COLOMBIA LTDA"],
    "PROMOTORA PARQUE SANTANDER S.A.": ["PROMOTORA PARQUE SANTANDER S.A."],
    "COMPAÑIA DE FINANCIAMIENTO TUYA S.A": ["COMPAÑIA DE FINANCIAMIENTO TUYA S.A"],
    "EMPRESA DE ENERGÍA DE BOYACÁ SA ESP": ["EMPRESA DE ENERGÍA DE BOYACÁ SA ESP"],
    "PROYECTO AGRUPADO BANCOLOMBIA": ["PROYECTO AGRUPADO BANCOLOMBIA"],
    "DIATECO SAS": ["DIATECO SAS"],
    "ECOPETROL CENTRAL 3031725": ["ECOPETROL CENTRAL 3031725"],
    "PERSPECTIVAS S.A.S.": ["PERSPECTIVAS S.A.S."],
    "ORLANDO PINILLA DIAZ": ["ORLANDO PINILLA DIAZ"],
    "PROMINERALES S.A.S": ["PROMINERALES S.A.S"],
    "BANCO DAVIVIENDA": ["BANCO DAVIVIENDA"],
};
