export const departamentosBase = {
    "Santander": ["Bucaramanga", "Floridablanca", "Piedecuesta", "Girón", "Barrancabermeja", "San Gil", "Vélez", "Socorro", "Málaga", "Barbosa", "Lebrija", "Rionegro", "Sabana de Torres", "El Socorro", "Puerto Wilches"],
    "Antioquia": ["Medellín", "Envigado", "Itagüí", "Bello", "Rionegro", "Caldas", "Sabaneta", "Copacabana", "Barbosa", "Girardota", "Apartadó", "Turbo", "Santa Fe de Antioquia", "Yarumal", "La Ceja"],
    "Cundinamarca": ["Bogotá", "Soacha", "Zipaquirá", "Chía", "Girardot", "Fusagasugá", "Facatativá", "Mosquera", "Madrid", "La Calera", "Tocancipá", "Cajicá", "Villeta", "Ubaté", "Guaduas"],
    "Valle del Cauca": ["Cali", "Palmira", "Buenaventura", "Tuluá", "Buga", "Cartago", "Jamundí", "Yumbo", "Santiago de Cali", "Guadalajara de Buga", "La Unión", "Roldanillo", "Sevilla", "Caicedonia", "Andalucía"],
    "Atlántico": ["Barranquilla", "Soledad", "Malambo", "Sabanalarga", "Puerto Colombia", "Polonuevo", "Baranoa", "Santo Tomás", "Palmar de Varela", "Sabanagrande", "Galapa", "Juan de Acosta", "Luruaco", "Tubará", "Repelón"],
    "Boyacá": ["Tunja", "Duitama", "Sogamoso", "Chiquinquirá", "Paipa", "Villa de Leyva", "Miraflores", "Puerto Boyacá", "Moniquirá", "Aquitania", "Tenza", "Sáchica", "Tibasosa", "Sutamarchán", "Garagoa"],
    "Bolívar": ["Cartagena", "Turbaco", "Magangué", "El Carmen de Bolívar", "Arjona", "María La Baja", "San Juan Nepomuceno", "Montecristo", "Calamar", "Mahates", "Santa Rosa del Sur", "San Jacinto", "Santa Catalina", "Villanueva", "Achí"],
    "Nariño": ["Pasto", "Tumaco", "Ipiales", "Túquerres", "La Cruz", "Barbacoas", "Cumbal", "Sandoná", "El Charquito", "Ancuya", "Samaniego", "Puerres", "Albán", "Guachucal", "Funes"],
    "Cauca": ["Popayán", "Santander de Quilichao", "Puerto Tejada", "Caloto", "Miranda", "Corinto", "Kahns", "El Tambo", "Silvia", "Piendamó", "Patía", "Balboa", "Guapi", "Inzá", "Jambaló"],
    "Meta": ["Villavicencio", "Acacías", "Granada", "Puerto López", "Puerto Gaitán", "Restrepo", "San Martín", "El Dorado", "Cumaral", "Castilla La Nueva", "San Juan de Arama", "Vista Hermosa", "Uribe", "Puerto Concordia", "Puerto Rico (Meta)"],
    "Cesar": ["Valledupar", "Aguachica", "Bosconia", "La Paz", "El Copey", "San Diego", "Chiriguaná", "Curumaní", "Pueblo Bello", "La Jagua de Ibirico", "San Alberto", "Gamarra", "Astrea", "Tamalameque", "Manaure Balcón del Cesar"],
    "Risaralda": ["Pereira", "Dosquebradas", "Santa Rosa de Cabal", "Marsella", "La Virginia", "Belén de Umbría", "Guática", "Quinchía", "Balboa", "Mistrató", "Apía", "Pueblo Rico", "Santuario", "La Celia"],
    "Huila": ["Neiva", "Pitalito", "Garzón", "Campoalegre", "La Plata", "Rivera", "Algeciras", "Baraya", "Tello", "Santa María", "Isnos", "San Agustín", "Suaza", "Yaguará", "Acevedo"],
    "Magdalena": ["Santa Marta", "Ciénaga", "Fundación", "Aracataca", "El Banco", "Plato", "Pivijay", "Sitio Nuevo", "Pueblo Viejo", "Zona Bananera", "Zona Bananera", "El Retén", "Puebloviejo", "Santa Ana", "Nueva Granada"],
    "Norte de Santander": ["Cúcuta", "Ocaña", "Pamplona", "Arauca", "Villa del Rosario", "Los Patios", "El Zulia", "San José de Cúcuta", "Tibú", "Teorama", "El Tarra", "La Esperanza", "Bochalema", "Sardinata", "Gramalote"],
    "Quindío": ["Armenia", "Calarcá", "La Tebaida", "Montenegro", "Quimbaya", "Circasia", "Salento", "Génova", "Buenavista", "Pijao", "Filandia", "Córdoba (Quindío)"],
    "Tolima": ["Ibagué", "Espinal", "Melgar", "Girardot", "Honda", "Chaparral", "Líbano", "Mariquita", "Guamo", "Purificación", "Rovira", "Icononzo", "Anzoátegui", "Ortega", "Coyaima"],
    "Chocó": ["Quibdó", "Istmina", "Condoto", "Nuquí", "Tadó", "Alto Baudó", "Medio Atrato", "Bahía Solano", "Unguía", "Río Quito", "Lloró", "Acandí", "Medio Baudó", "San José del Palmar", "Bajo Baudó"],
    "Córdoba": ["Montería", "Lorica", "Cereté", "Sahagún", "Ciénaga de Oro", "San Carlos", "San Antero", "Pueblo Nuevo", "Puerto Escondido", "Purísima", "Tierralta", "Montelíbano", "Planeta Rica", "Ayapel", "Chinú"],
    "Sucre": ["Sincelejo", "Corozal", "Sampués", "Ovejas", "San Marcos", "Guaranda", "Chalán", "San Benito Abad", "La Unión", "Majagual", "Tolú", "San Onofre", "Palmito", "Toluviejo", "Coveñas"],
    "Caldas": ["Manizales", "Villamaría", "Chinchiná", "Palestina", "Neira", "Aranzazu", "Salamina", "Pensilvania", "Risaralda", "Manzanares", "Filadelfia", "La Merced", "San José", "Pácora", "Marquetalia"],
    "Casanare": ["Yopal", "Aguazul", "Tauramena", "Paz de Ariporo", "Villanueva", "Monterrey", "Hato Corozal", "Nunchía", "San Luis de Palenque", "Trinidad", "Sabanalarga (Casanare)", "Chámeza", "Recetor", "La Salina", "Pore"],
    "La Guajira": ["Riohacha", "Maicao", "Uribia", "Dibulla", "Manaure", "Albania", "Hatonuevo", "Fonseca", "Distracción", "San Juan del Cesar", "Barrancas", "Urumita", "La Jagua del Pilar", "Villanueva"],
    "Arauca": ["Arauca", "Saravena", "Arauquita", "Fortul", "Puerto Rondón", "Cravo Norte", "Tame", "Puerto Jordán"],
    "Putumayo": ["Mocoa", "Puerto Asís", "Valle del Guamuez", "Orito", "Puerto Caicedo", "San Miguel", "Puerto Guzmán", "Villagarzón", "Leguízamo", "Santiago", "Colón", "San Francisco", "Puerto Leguízamo"],
    "Caquetá": ["Florencia", "San Vicente del Caguán", "Belén de los Andaquíes", "Cartagena del Chairá", "Puerto Rico", "El Doncello", "Currillo", "La Montañita", "Morelia", "Solita", "San José del Fragua", "Solano", "Milán"],
    "Amazonas": ["Leticia", "Puerto Nariño", "El Encanto", "La Chorrera", "La Pedrera", "Mirití-Paraná", "Puerto Santander", "Tarapacá", "Puerto Alegría", "Puerto Arica"],
    "Guainía": ["Puerto Inírida", "Barranco Minas", "San Felipe", "Cacahual", "Moyobamba", "Morichal", "Puinawai", "Mapiripana"],
    "Guaviare": ["San José del Guaviare", "El Retorno", "Calamar", "Miraflores", "La Libertad"],
    "Vaupés": ["Mitú", "Carurú", "Taraira", "Pacoa", "Papunahua", "Yavaraté", "Yavaraté"],
    "San Andrés y Providencia": ["San Andrés", "Providencia"],
    "Vichada": ["Puerto Carreño", "Santa Rosalía", "La Primavera", "Cumaribo", "San José de Ocune", "Santa Rita", "Guaripa"]
};
