export const departamentosBase = {
    "Santander": ["Bucaramanga", "Floridablanca", "Piedecuesta", "Girón", "Barrancabermeja", "San Gil", "Vélez", "Socorro", "Málaga", "Barbosa"],
    "Antioquia": ["Medellín", "Envigado", "Itagüí", "Bello", "Rionegro", "Caldas", "Sabaneta", "Copacabana", "Barbosa", "Girardota"],
    "Cundinamarca": ["Bogotá", "Soacha", "Zipaquirá", "Chía", "Girardot", "Fusagasugá", "Facatativá", "Mosquera", "Madrid", "La Calera"],
    "Valle del Cauca": ["Cali", "Palmira", "Buenaventura", "Tuluá", "Buga", "Cartago", "Jamundí", "Yumbo", "Santiago de Cali", "Guadalajara de Buga"],
    "Atlántico": ["Barranquilla", "Soledad", "Malambo", "Sabanalarga", "Puerto Colombia", "Polonuevo", "Baranoa", "Santo Tomás", "Palmar de Varela", "Sabanagrande"],
    "Boyacá": ["Tunja", "Duitama", "Sogamoso", "Chiquinquirá", "Paipa", "Villa de Leyva", "Miraflores", "Puerto Boyacá", "Moniquirá", "Aquitania"],
    "Bolívar": ["Cartagena", "Turbaco", "Magangué", "El Carmen de Bolívar", "Arjona", "María La Baja", "San Juan Nepomuceno", "Montecristo", "Calamar", "Mahates"],
    "Nariño": ["Pasto", "Tumaco", "Ipiales", "Túquerres", "La Cruz", "Barbacoas", "Cumbal", "Sandoná", "El Charquito", "Ancuya"],
    "Cauca": ["Popayán", "Santander de Quilichao", "Puerto Tejada", "Caloto", "Miranda", "Corinto", "Kahns", "El Tambo", "Silvia", "Piendamó"],
    "Meta": ["Villavicencio", "Acacías", "Granada", "Puerto López", "Puerto Gaitán", "Restrepo", "San Martín", "El Dorado", "Cumaral", "Castilla La Nueva"],
    "Cesar": ["Valledupar", "Aguachica", "Bosconia", "La Paz", "El Copey", "San Diego", "Chiriguaná", "Curumaní", "Pueblo Bello", "La Jagua de Ibirico"],
    "Risaralda": ["Pereira", "Dosquebradas", "Santa Rosa de Cabal", "Marsella", "La Virginia", "Belén de Umbría", "Guática", "Quinchía", "Balboa", "Mistrató"],
    "Huila": ["Neiva", "Pitalito", "Garzón", "Campoalegre", "La Plata", "Rivera", "Algeciras", "Baraya", "Tello", "Santa María"],
    "Magdalena": ["Santa Marta", "Ciénaga", "Fundación", "Aracataca", "El Banco", "Plato", "Pivijay", "Sitio Nuevo", "Pueblo Viejo", "Zona Bananera"],
    "Norte de Santander": ["Cúcuta", "Ocaña", "Pamplona", "Arauca", "Villa del Rosario", "Los Patios", "El Zulia", "San José de Cúcuta", "Tibú", "Teorama"],
    "Quindío": ["Armenia", "Calarcá", "La Tebaida", "Montenegro", "Quimbaya", "Circasia", "Salento", "Génova", "Buenavista", "Córdoba"],
    "Tolima": ["Ibagué", "Espinal", "Melgar", "Girardot", "Honda", "Chaparral", "Líbano", "Mariquita", "Guamo", "Purificación"],
    "Chocó": ["Quibdó", "Istmina", "Condoto", "Nuquí", "Tadó", "Alto Baudó", "Medio Atrato", "Bahía Solano", "Unguía", "Río Quito"],
    "Córdoba": ["Montería", "Lorica", "Cereté", "Sahagún", "Ciénaga de Oro", "San Carlos", "San Antero", "Pueblo Nuevo", "Puerto Escondido", "Purísima"],
    "Sucre": ["Sincelejo", "Corozal", "Sampués", "Ovejas", "San Marcos", "Guaranda", "Chalán", "San Benito Abad", "La Unión", "Majagual"],
    "Caldas": ["Manizales", "Villamaría", "Chinchiná", "Palestina", "Neira", "Aranzazu", "Salamina", "Pensilvania", "Risaralda", "Manzanares"],
    "Casanare": ["Yopal", "Aguazul", "Tauramena", "Paz de Ariporo", "Villanueva", "Monterrey", "Hato Corozal", "Nunchía", "San Luis de Palenque", "Trinidad"],
    "La Guajira": ["Riohacha", "Maicao", "Uribia", "Dibulla", "Manaure", "Albania", "Hatonuevo", "Fonseca", "Distracción", "San Juan del Cesar"],
    "Arauca": ["Arauca", "Saravena", "Arauquita", "Fortul", "Puerto Rondón", "Cravo Norte", "Tame"],
    "Putumayo": ["Mocoa", "Puerto Asís", "Valle del Guamuez", "Orito", "Puerto Caicedo", "San Miguel", "Puerto Guzmán", "Villagarzón", "Leguízamo", "Santiago"],
    "Caquetá": ["Florencia", "San Vicente del Caguán", "Belén de los Andaquíes", "Cartagena del Chairá", "Puerto Rico", "El Doncello", "Currillo", "La Montañita", "Morelia", "Solita"],
    "Amazonas": ["Leticia", "Puerto Nariño", "El Encanto", "La Chorrera", "La Pedrera", "Mirití-Paraná", "Puerto Santander", "Tarapacá"],
    "Guainía": ["Puerto Inírida", "Barranco Minas", "San Felipe", "Cacahual", "Moyobamba", "Morichal"],
    "Guaviare": ["San José del Guaviare", "El Retorno", "Calamar", "Miraflores"],
    "Vaupés": ["Mitú", "Carurú", "Taraira", "Pacoa", "Papunahua", "Yavaraté"],
    "San Andrés y Providencia": ["San Andrés", "Providencia"],
    "Vichada": ["Puerto Carreño", "Santa Rosalía", "La Primavera", "Cumaribo"]
};
